FROM ruby:2.6.3
ENV LANG C.UTF-8
ENV APP_HOME /myapp

RUN apt-get update -qq && apt-get install -y \
    build-essential \
    nodejs \
    default-libmysqlclient-dev\
 && rm -rf /var/lib/apt/lists/*

RUN gem install bundler

WORKDIR /tmp
ADD Gemfile Gemfile
ADD Gemfile.lock Gemfile.lock
RUN bundle install



RUN mkdir -p $APP_HOME
WORKDIR $APP_HOME
ADD . $APP_HOME

RUN gem install mysql2 -v '0.5.2' --source 'https://rubygems.org/'
